//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.BasicInfo = new HashSet<BasicInfo>();
        }
    
        public int IdCandidate { get; set; }
        public int IdEducation { get; set; }
        public Nullable<int> IdWorkExperience { get; set; }
        public Nullable<int> IdProfessionalSkills { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> MobilePhone { get; set; }
        public int HomePhone { get; set; }
        public string Skype { get; set; }
        public System.DateTime BirtchDate { get; set; }
        public string Residence { get; set; }
        public string MilitaryAttitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicInfo> BasicInfo { get; set; }
        public virtual Education Education { get; set; }
        public virtual ProfessionalSkills ProfessionalSkills { get; set; }
        public virtual WorkExperience WorkExperience { get; set; }
    }
}
