//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Education()
        {
            this.Candidate = new HashSet<Candidate>();
        }
    
        public int IdEducation { get; set; }
        public int IdKnowledgeOfLanguages { get; set; }
        public string EducationalEstablishment { get; set; }
        public string DegreeInformation { get; set; }
        public System.DateTime AdmissionYear { get; set; }
        public System.DateTime GraduationYear { get; set; }
        public string PostgraduateWork_ForBY_ { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string EducationForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual KnowledgeOfLanguages KnowledgeOfLanguages { get; set; }
    }
}
