//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecruitmentDBEntities : DbContext
    {
        public RecruitmentDBEntities()
            : base("name=RecruitmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidate { get; set; }
        public virtual DbSet<DetailedSkill> DetailedSkill { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<KnowledgeOfLanguages> KnowledgeOfLanguages { get; set; }
        public virtual DbSet<ProfessionalSkills> ProfessionalSkills { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<WorkExperience> WorkExperience { get; set; }
        public virtual DbSet<BasicInfo> BasicInfo { get; set; }
    }
}
