//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalSkills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfessionalSkills()
        {
            this.Candidate = new HashSet<Candidate>();
        }
    
        public int IdProfessionalSkills { get; set; }
        public int IdSkill { get; set; }
        public string YearsOfExperience { get; set; }
        public string AdditionalInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidate { get; set; }
        public virtual Skills Skills { get; set; }
    }
}
